### ISSUE TITLE
Signature does not match.

### ISSUE THREAD

**Issue by Firstbober** [pydio/cells-sync#34]
I deployed my own instance of Pydio Cells home using docker behind nginx reverse proxy, everything works fine from web interface, but Cell Sync client constantly shows error: `The request signature we calculated does not match the signature you provided. Check your key and signing method.`.
This makes syncing files impossible, I tried tweaking with cells server and nginx itself but nothing helps.

**Comment by cdujeu** [comment]
hi @Firstbober could you kindly post in the forum instead of opening an issue : most probably a configuration problem, and we keep github issues only for "qualified" bugs. Thanks in advance!
PS : also make sure to post all the info you can about your setup (cells version, how the proxy is configured, etc...)

**Comment by Firstbober** [comment]
Sure.
